CREATE TABLE IF NOT EXISTS DICTIONARY(
  id INT AUTO_INCREMENT PRIMARY KEY,
  word VARCHAR(100) NOT NULL,
  pos_id INT NOT NULL,
  position INT NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTINGS(
  pos_id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(90) NOT NULL,
  dir VARCHAR(10) NOT NULL,
  href VARCHAR(100) NOT NULL
);